### ISSUE TITLE
VP0 won’t start

### ISSUE THREAD

**Issue by ericmvaughn** [IBM-Blockchain/ibm-blockchain-issues#27]
After running successfully for several days my VP0 stopped and I’m unable to start it.  When I issue the restart it goes to loading and then quickly back to Stopped.  I also tried to restart all of the VPs and MS nodes but VP0 still wouldn’t start.  

![image](https://cloud.githubusercontent.com/assets/14101498/18092732/660d5c98-6e9b-11e6-80d2-00896c113988.png)

**Comment by dshuffma-ibm** [comment]
did anything improve? I can no longer find this network to help, its probably been deleted.

**Comment by ericmvaughn** [comment]
I just checked and all 4 of the peers and the ms are there and running.  The REST interface and chaincode queries are working fine but for some reason my invokes aren't working.  However, the original issue of VP0 not running seems to have resolved itself somehow.

**Comment by dshuffma-ibm** [comment]
interesting, since vp0 is up i'm going to close this issue.  as for why it stopped its likely because we had stability issues awhile ago and your peer could have been one of the ones affected.  we probably recovered your peer during our fire-fighting process.

if you can't resolve the invoke issue then open a new one targeting that.  peer logs and the name of the chaincode you are using would be helpful.

**Comment by ericmvaughn** [comment]
Thanks for the update and I'll open a new issue for the invoke if I'm unable to get it working.
