### ISSUE TITLE
why chaincode_example02 failed  to work the second time

### ISSUE THREAD

**Issue by git123456** [IBM-Blockchain/ibm-blockchain-issues#39]
@angrbrd @dshuffma-ibm @mrshah-at-ibm ... Hi this is related to issue 32, I thought to create a new issue specific for bluemix.  .... now that I am stuck with bluemix blockchain only, I tried to deployed chaincode_example02 again, with shim interface 0.5 version,  but it seems to fail this time, it "seems" to deploy with a chaincode id returned, but failed when I tried to query it.  But a few day ago I was able to deploy and query the same codes (pretty sure it is the same code, anyway attached here).  I checked the peer_0 log.. no obvious errors showing, did see this "Did not handle message of type DISC_PEERS, passing on to next MessageHandler" which I don't know if it mattered.  On the client site, the query for 'a' failed and the error message was "Error:Failed to launch chaincode spec(Error starting container: API error (500): Error: image library/809d944f-85b3-40c2-a5ca-0479b138594d-vp0-14e096a66da0ddffe2d36a972c3a1a59f6ac430144487a49621c75e8d400326f not found\n)"

Can you advice what to do next?  Or how to debug?

p/s note I did try to  deploy a few more times, all returned chaincode id but failed when trying to query (that implied the deployment didn't really work, I guess).

[chaincode_example02.txt](https://github.com/IBM-Blockchain/ibm-blockchain-issues/files/485514/chaincode_example02.txt)

**Comment by dshuffma-ibm** [comment]
Hello again!

I built your go code, seems fine (have not tried deploying it yet). You may be interested in using this version instead: https://github.com/IBM-Blockchain/marbles-chaincode/blob/master/hyperledger/part2/part2_chaincode.go This is the version our demo tab uses.

here are a few easy things to try:
1. wait longer - wait as long as 5 minutes after you see the response to the deploy.  it can occasionally take forever to finish deploying.
2. try the demo tab in the dashboard - the demo tab's ex02 works. and should give you "proof of life" for your network. when this fails, grab a new network.
3. grab a new network anyway - its a free service, grab another one whenever you see something unexpected. occasionally some networks will just be broken... we are better than we were at this, we do attempt to make sure a network looks good before handing it to you, but it can still happen.

you are correct about the deploy response behavior, just b/c you got an id back does not mean everything was successful.

**Comment by TarantulaTechnology** [comment]
I am receiving the same ERROR when I query after a deploy that returns "OK" and an ID. Prior to the IBM Blockchain upgrade from v0.4.1 to v0.4.2 it worked. So my guess is it is related to something that changed or tasks being performed that are disrupting and sporadically creating anomalies that make no sense. Even /registrar is now returning inconsistent responses. I have tried new networks too, but to no avail, it's just broke. But hey! It is BETA :) I'll try compiling the above too, because the fabric code on github is not v0.5, it contains the code for v0.6 which is not backward compatible.

Ok, tried compiling the above and it fails (see below). But if I point it to my clone of fabric v0.5 it compiles. So I don't think there is anything wrong with the code if you are using the v0.5 fabric. And fabric v0.5 is / was running as IBM Blockchain on BMX as of Sep 7th. 

I was able to publicly compile, deploy, and demo simple chaincode on Sep 7th,  based on the IBM chaincode examples; IBM Blockchain was at v0.4.1. I am not saying it was the upgrade that broke it. I personally tend to believe engineers are working on the infrastructure and support code so things are going to break and drive one crazy if you expect non-functional performance like reliability, consistency, and resilience. I would expect these issues to be just beta pains and the first release will change the state of expectations.

Until then, we just have to...each day start new, and expect little :)

Here I try to compile with: github.com/hyperledger/fabric/core/chaincode/shim

marksmacbookpro:finished markmorris$ go build ./chaincode_example02.go
# command-line-arguments
./chaincode_example02.go:181: cannot use new(SimpleChaincode) (type _SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
        *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
                have Init(_shim.ChaincodeStub, string, []string) ([]byte, error)
                want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)

Note: ChaincodeStubInterface is the new code in the upcoming v0.6 release.

Here I changed github.com/hyperledger/fabric/core/chaincode/shim to github.com/TarantulaTechnology/fabric/core/chaincode/shim, which is a clone of fabric 0.5 from the archives

marksmacbookpro:finished markmorris$ go build ./chaincode_example02.go
marksmacbookpro:finished markmorris$ 

And it compiles :)

The nature of the ERROR message leads me to think the BMX / IBM Blockchain infrastructure is experiencing technical issues out of the control of users.

**Comment by dshuffma-ibm** [comment]
I think the service is just overloaded, please wait up to 10 minutes....

This is what I've been doing and its worked 3 times in a row:
1. get a new network
2. go to demo tab and deploy example02,  keep this browser tab open. do not query yet
3. open a new one for the "Network" tab. increase the auto refresh to 5 seconds (on the bottom)

and wait for the number of peers that have our chaincode to tick up to 4
![image](https://cloud.githubusercontent.com/assets/16085295/18751651/bd07bd76-80ad-11e6-98a9-62bef561da48.png)

and waiting...
![image](https://cloud.githubusercontent.com/assets/16085295/18751659/c4f30612-80ad-11e6-9f06-7ab2e4ffdbda.png)

now we have 4, but the status still says `exited` which is worrying so keep waiting...
![image](https://cloud.githubusercontent.com/assets/16085295/18751771/3e73d17e-80ae-11e6-9384-0ec6df38b1b2.png)

ok looking good now
![image](https://cloud.githubusercontent.com/assets/16085295/18751813/60b81632-80ae-11e6-87b9-6b36fb4908da.png)

now go back to the demo tab and query on the A and B and send some invokes:
![image](https://cloud.githubusercontent.com/assets/16085295/18751837/7c99dc5a-80ae-11e6-9737-a132bc161eaa.png)

everything looks good, it's just really slow. this flow took between 6 - 9 minutes.

**Comment by git123456** [comment]
@dshuffma-ibm if more than two days is long enough?  I tried to do a retrieve and it still failed.  You said you were successfully compile my code, why not go all the way to deploy to bluemix yourself to see what happen?  I guess I am the only having this problem hence I think it is worth trying out yourself?  Then if you were successfully deployed to your bluemix then I can give you my credential to have you to deploy to my bluemix.

BTW, this is how I get a chain let me know if you see problem :
          var hfc = require('hfc');  //I did verify it is @0.5.3
          var chain = hfc.newChain("testChain");
       var pem = fs.readFileSync('us.blockchain.ibm.com.cert');  //did verify file existed
           chain.setMemberServicesUrl("grpcs://809d944f-85b3-40c2-a5ca-0479b138594d_ca.us.blockchain.ibm.com:30303", {pem:pem});
           chain.addPeer("grpcs://809d944f-85b3-40c2-a5ca-0479b138594d_vp0.us.blockchain.ibm.com:30303", {pem:pem});

**Comment by mastersingh24** [comment]
closing this as it applies to old version(s) of the BMX starter plan which no longer exist.
we also addressed the performance issues in the new deployment topology for the latest version of the starter plan
