### ISSUE TITLE
Cannot recover from 'Error: state may be inconsistent cannot query'.

### ISSUE THREAD

**Issue by tribbloid** [IBM-Blockchain/ibm-blockchain-issues#49]
The blockchain service encounter an unrecoverable 'Error: state may be inconsistent cannot query' error and cannot be queried after waiting for a long time, likely to be caused by different execution result on each VP.

This error message appears to all kinds of invokes & queries, including demo chaincodes. There is a chance that invokes may return with success messages, but the payload won't be processed or visible on UI.

The blockchain has since been mothballed and no transaction has been written into it.

blockchain ID: 5f3d4b1f-0909-452e-90e7-42ffe8e439c7

We've moved on to another factory reset service, but I'll keep the service up for your convenience, please let us know if you need more log files or diagnoses.

All the best,

Yours Peng

**Comment by mrshah-at-work** [comment]
@tribbloid yes, this can happen due to different execution result on each VP or inability to deploy due to different reasons.

We have updated the bluemix service to v0.6 of fabric and also addressed the stability issues. Please let us know if you see the issue again. Closing the issue now, please re-open if you see it again.
