### ISSUE TITLE
If the service uptime is less than 100% should we raise application issues?

### ISSUE THREAD

**Issue by gregmisiorek** [IBM-Blockchain/ibm-blockchain-issues#55]
i'm not getting expected results or only invalid ones when deploying and trying to 'Select the correct chaincode:' dropbox, but if the service itself is not up, the specific application issue can only be a reflection of the service being down, can it not?

**Comment by mastersingh24** [comment]
@gregmisiorek  - the chaincode issues have to do with it taking an exceptionally long time to deploy chaincode due to the current number of service instances we are managing.  We just added some new capacity on a separate infrastructure which should vastly improve things when it comes to deploying chaincode
